import { pipeline, env } from '@huggingface/transformers';
import fs from 'fs';
env.allowRemoteModels=false;
env.localModelPath=process.env.STT+'/node_modules/sts-whisper-small/models/';
const asr = await pipeline('automatic-speech-recognition','Xenova/whisper-small',{dtype:'q8',device:'cpu'});
const buf=fs.readFileSync(process.argv[3]);
const audio=new Float32Array(buf.buffer,buf.byteOffset,buf.length/4);
const mode=process.argv[2]||'word';
const out=await asr(audio,{language:'korean',task:'transcribe',chunk_length_s:30,stride_length_s:5,return_timestamps: mode==='word'?'word':true});
fs.writeFileSync(process.argv[4],JSON.stringify(out,null,1));
console.log(out.text);
if(mode!=='word') for(const c of out.chunks) console.log(c.timestamp, c.text);
